### ISSUE TITLE
请问现在还能用么？授权的时候PermissionDenied

### ISSUE THREAD

**Issue by yutao8** [bohewei/SKY#1]
```json
{"errormsg":"PermissionDenied","success":false}
```
请问我是少了什么步骤么？应用是在 [http://cloud.189.cn/developer.action](http://cloud.189.cn/developer.action) 申请的，没有提交审核，已经添加测试账号

**Comment by bohewei** [comment]
天翼云SDK已经不维护了，如果天翼云官方没有更改文档，SDK还能使用。
你的报错是访问权限不足，应用权限：普通 -只能调用以应用名命名的文件夹内数据。

**Comment by yutao8** [comment]
我点了去授权就变成这个样子了，还没登账号呢
